import Head from "next/head";
import { Inter } from "next/font/google";
import Datatable from "@/components/Datatable";
import { GET_USERS_DATA, type userType } from "@/helpers/api";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  let dt = await GET_USERS_DATA();
  return {
    props: { dt: (dt as userType[]) || [] }, // will be passed to the page component as props
  };
}

export default function Home({ dt }: { dt: userType[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-2 px-4 flex flex-col w-full h-full bg-gray-50">
        <h1 className="text-3xl font-semibold text-green-600 lg:mt-10 lg:ml-10">
          Welcome
        </h1>
        <div className="mt-10 w-full">
          <Datatable records={dt}></Datatable>
        </div>
      </main>
    </>
  );
}
